# Generated by Django 5.0.3 on 2024-06-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_artikel_created_at_artikel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='slug',
        ),
    ]
