# Generated by Django 5.0.3 on 2024-06-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_rename_created_at_artikel_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
