# Generated by Django 5.0.3 on 2024-06-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_rename_create_at_artikel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
